a,b=5,2
print('a=:',a)
print('b=',b)
print('Addition:', a+b)
print('Subtraction:', a-b)
print('Multiplication:', a*b)
print('Division:', a/b)
print('Modulus:', a%b)
print('Exponential:', a**b)
print('Floor Division:', a//b)
