a=int(input('Enter first number:'))
b=int(input('Enter second nnumber:'))
print('Addition of two numbers:', a+b)
print('Substraction of two numbers:', a-b)
print('Multiplication of two numbers:', a*b)
print('Division of two numbers:', a/b)
print('Power of %d to %d is:%d'%(a,b,a**b))
print('Floor Division of two numbers:', a+b)
print('Modulus of two numbers:', a%b)
